# TensorFlow Basics

In [27]:
import tensorflow as tf

In [28]:
# Make sure you are using 1.3 for exact sytnax matching!
print(tf.__version__)

1.3.0


## Tensors

In [3]:
hello = tf.constant('Hello')

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
world = tf.constant('World')

In [6]:
result = hello + world

In [7]:
result

<tf.Tensor 'add:0' shape=() dtype=string>

In [8]:
type(result)

tensorflow.python.framework.ops.Tensor

In [9]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [10]:
result

b'HelloWorld'

** Computations **

In [11]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [12]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [13]:
tensor_1 + tensor_2

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [14]:
sess

In [15]:
sess.close()

## Operations

In [16]:
const = tf.constant(10)

In [17]:
fill_mat = tf.fill((4,4),10)

In [18]:
myzeros = tf.zeros((4,4))

In [19]:
myones = tf.ones((4,4))

In [20]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [21]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [22]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

## Interactive Session

Useful for Notebook Sessions

In [23]:
# Only run this cell once!
sess = tf.InteractiveSession()

In [24]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 0.22629221 -0.0112013  -0.03795577  0.12235507]
 [-0.1088447   0.0319506  -0.36833972  0.62197924]
 [ 0.51775289  0.29777035 -0.70367879 -0.07881669]
 [ 0.56051242  1.21852517  0.13774575 -0.08752721]]


[[ 0.92519712  0.15601957  0.3870616   0.3412255 ]
 [ 0.33955777  0.43507528  0.80543637  0.01599467]
 [ 0.73546493  0.38525558  0.99109244  0.12037551]
 [ 0.38074708  0.4369998   0.53943872  0.89470959]]




## Matrix Multiplication

In [26]:
x = tf.random_normal([1,2,3])
print(x.eval())

[[[ -1.86264217e-01   7.95095623e-01  -1.70354831e+00]
  [  3.90942305e-01  -1.63700595e-03   1.44036055e-01]]]


In [58]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [59]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [60]:
b = tf.constant([[10],[100]])

In [61]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [62]:
result = tf.matmul(a,b)

In [63]:
result.eval()

array([[210],
       [430]])