# TensorFlow Basics

In [1]:
import tensorflow as tf

In [2]:
# Make sure you are using 1.3 for exact sytnax matching!
print(tf.__version__)

1.3.0


## Tensors

In [3]:
hello = tf.constant('Hello')

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
world = tf.constant('World')

In [6]:
result = hello + world

In [7]:
result

<tf.Tensor 'add:0' shape=() dtype=string>

In [8]:
type(result)

tensorflow.python.framework.ops.Tensor

In [9]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [10]:
result

b'HelloWorld'

** Computations **

In [11]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [12]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [13]:
tensor_1 + tensor_2

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [14]:
sess

In [15]:
sess.close()

## Operations

In [16]:
const = tf.constant(10)

In [17]:
fill_mat = tf.fill((4,4),10)

In [18]:
myzeros = tf.zeros((4,4))

In [19]:
myones = tf.ones((4,4))

In [20]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [21]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [22]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

## Interactive Session

Useful for Notebook Sessions

In [23]:
# Only run this cell once!
sess = tf.InteractiveSession()

In [24]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[-1.11214924  0.71156144  0.16964507 -1.23660791]
 [-0.06922308  0.35488182 -0.33090201 -0.61503905]
 [-0.87933153  0.26639426  0.0825633   0.13088021]
 [ 0.01259506 -0.38394609  0.03613659 -0.62586278]]


[[ 0.98276258  0.23459983  0.47957551  0.5522126 ]
 [ 0.89894032  0.27657747  0.01370859  0.98019814]
 [ 0.24030602  0.15225148  0.49768317  0.09391332]
 [ 0.40990615  0.23983276  0.74029088  0.90023184]]




## Matrix Multiplication

In [58]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [59]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [60]:
b = tf.constant([[10],[100]])

In [61]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [62]:
result = tf.matmul(a,b)

In [63]:
result.eval()

array([[210],
       [430]])