In [1]:
import tensorflow as tf

In [2]:
var1 = tf.constant(3.0)
var2 = tf.constant(3)
sess = tf.Session()
print(var1,tf.float32)
print(var2)
print (sess.run(var1))
print (sess.run(var2))
print (sess.run([var1, var2]))


Tensor("Const:0", shape=(), dtype=float32) <dtype: 'float32'>
Tensor("Const_1:0", shape=(), dtype=int32)
3.0
3
[3.0, 3]


In [3]:
var3 = tf.constant(4.0)
node_add = tf.add(var1,var3) #必须都是tf.float32，否则不能相加
print(node_add)
print(sess.run(node_add))

Tensor("Add:0", shape=(), dtype=float32)
7.0


In [25]:
n_features = 3
n_labels = 2
w = tf.Variable(tf.truncated_normal((3, 2)))
init = tf.global_variables_initializer()
sess.run(init)
print(sess.run(w))

[[ 1.49697721  1.10796535]
 [-0.49764538 -0.57008994]
 [-1.11214149  0.37714601]]


In [26]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
c = a+b
print(sess.run(c,{a:2.5,b:2.0}))

4.5


In [27]:
print(sess.run(2*c, {a:[1.0,2.0], b:[3.4, 4.4]}))

[  8.80000019  12.80000019]


In [28]:
W = tf.Variable([1.1],tf.float32)
print(W)

Tensor("Variable_4/read:0", shape=(1,), dtype=float32)


In [29]:
b = tf.Variable([2.0],tf.float32)
x = tf.placeholder(tf.float32)
y = W*x + b

n_features = 3
n_labels = 2
weights = tf.Variable(tf.truncated_normal((n_features, n_labels)))
#The tf.truncated_normal() function returns a tensor with random values
#from a normal distribution whose magnitude is no more than 2 standard deviations from the mean.

In [30]:
#By contrast, variables are not initialized when you call tf.
#Variable. To initialize all the variables in a TensorFlow program, you must explicitly call a special operation as
init = tf.global_variables_initializer()
sess.run(init)
print(sess.run(W)) #如果没有init,不能直接运行sess.run(W)

[ 1.10000002]


In [31]:
sess.run(init)

In [32]:
print(sess.run(y, {x:[1,2,3,4]}))

[ 3.0999999   4.19999981  5.30000019  6.4000001 ]


In [33]:
print(sess.run(weights))


[[-0.16208541 -0.96316862]
 [ 1.85286367 -0.53191882]
 [ 0.26415733  0.36957261]]


In [34]:
a = tf.reduce_sum([1,2,3,4])
print(sess.run(a))

10


In [35]:
logit_data = [2.0, 1.0, 0.1]
softmax = tf.nn.softmax(logit_data)
print(sess.run(softmax))

[ 0.65900117  0.24243298  0.09856589]
